name = "president-api"
main = "src/api/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

[env.production]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "president-db"
database_id = "your-database-id"

# KV Namespace bindings
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-id"
preview_id = "your-kv-id"

[[kv_namespaces]]
binding = "LOBBIES"
id = "your-kv-id"
preview_id = "your-kv-id"

# Environment variables
[vars]
ENV = "production"
