# This file is a placeholder. Use wrangler.api.toml and wrangler.realtime.toml for separate workers.
# Or you can configure a single worker with both handlers here.

name = "president"
main = "src/index.ts"
compatibility_date = "2024-01-15"
node_compat = true

# See wrangler.api.toml and wrangler.realtime.toml for actual configuration
# Run: pnpm run dev:api or pnpm run dev:realtime
