name = "president-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Bindings from global wrangler.toml
[[d1_databases]]
binding = "DB"
database_name = "president-db"
database_id = "your-database-id-here"

[[kv_namespaces]]
binding = "LOBBY_KV"
id = "your-lobby-kv-id-here"

[[kv_namespaces]]
binding = "PRESENCE_KV"
id = "your-presence-kv-id-here"

[vars]
ENVIRONMENT = "development"
JWT_SECRET = "your-jwt-secret-here"

